added admin and regular user audit log

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -27,4 +27,7 @@ npm run knip || { echo '❌ Dependency check for static resources failed.'; exit
 echo '➡️ build'
 npm run build || { echo '❌ Build failed'; popd > /dev/null; exit 1; }
 
+echo '➡️ lint check'
+npm run lint || { echo '❌ lint check failed.'; exit 1; }
+
 popd > /dev/null
