Refactor pre-commit script and comment out unused scheduled trigger configuration

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+echo '➡️ <--- BUILD BACKEND --->'
 echo '🔍 Running resolver checks...'
 
 echo '➡️ lint-staged (resolver)'
@@ -15,41 +16,41 @@ echo '➡️ lint check'
 npm run lint || { echo '❌ lint check failed.'; exit 1; }
 echo '➡️ lint check'
 npm run test || { echo '❌ tests failed.'; exit 1; }
-
+echo '➡️ <--- BUILD FRONTEND --->'
 echo '🔍 Running static resources checks...'
-pushd static > /dev/null
+cd static
 
 echo '➡️ lint-staged (static resources)'
-npx lint-staged || { echo '❌ lint-staged failed for static resources'; popd > /dev/null; exit 1; }
+npx lint-staged || { echo '❌ lint-staged failed for static resources'; cd ..; exit 1; }
 
 
 echo '➡️ dependencies check'
-npm run knip || { echo '❌ Dependency check for static resources failed.'; exit 1; }
+npm run knip || { echo '❌ Dependency check for static resources failed.'; cd ..; exit 1; }
 
 echo '➡️ build'
-npm run build || { echo '❌ Build failed'; popd > /dev/null; exit 1; }
+npm run build || { echo '❌ Build failed'; cd ..; exit 1; }
 
 echo '➡️ lint check'
 npm run lint || { echo '❌ lint check failed.'; exit 1; }
 
-popd > /dev/null
-
-pushd web-site > /dev/null
+cd ..
+echo '➡️ <--- BUILD SITE --->'
+cd web-site
 
 echo '➡️ npm audit (resolver)'
 npm audit fix|| { echo '❌ audit not fixed'; exit 1; }
 
 echo '➡️ lint-staged (static resources)'
-npx lint-staged || { echo '❌ lint-staged failed for static resources'; popd > /dev/null; exit 1; }
+npx lint-staged || { echo '❌ lint-staged failed for static resources'; cd ..; exit 1; }
 
 
 echo '➡️ dependencies check'
 npm run knip || { echo '❌ Dependency check for static resources failed.'; exit 1; }
 
 echo '➡️ build'
-npm run build || { echo '❌ Build failed'; popd > /dev/null; exit 1; }
+npm run build || { echo '❌ Build failed'; cd ..; exit 1; }
 
 echo '➡️ lint check'
 npm run lint || { echo '❌ lint check failed.'; exit 1; }
 
-popd > /dev/null
+cd ..
